theme: jekyll-theme-minimal
title: Algoritmi e Informatica di Base
description: Primo progetto di Informatica presso il Liceo "I. Kant" di Melito di Napoli
show_downloads: True
navigation:
  - title: Home
    url: /pages/home
    
  - title: Team
    url: /pages/team
    
  - title: Jupyter
    url: /pages/jupyter
    
  - title: Utilities
    url: /pages/utilities   
    
  - title: Extra
    url: /pages/extra   
