theme: jekyll-theme-minimal
title: Algoritmi e Informatica di Base
description: Primo progetto di Informatica presso il Liceo "I. Kant" di Melito di Napoli
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Team
    url: Team
